# Generated by Django 6.0.6 on 2026-06-21 15:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_membro', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('ADMIN', 'Administrador')], max_length=20)),
                ('ra', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('siape', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('qtd_total', models.PositiveIntegerField(default=1, verbose_name='quantidade total')),
                ('qtd_disponivel', models.PositiveIntegerField(default=1, verbose_name='quantidade disponível')),
                ('disponivel', models.BooleanField(default=True)),
                ('autores', models.ManyToManyField(related_name='Livros', to='biblioteca.autor')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Livros', to='biblioteca.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_prevista_devolucao', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], default='EMPRESTADO', max_length=20)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_emprestados', to='biblioteca.livro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_emprestados', to='biblioteca.membro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
