# Generated by Django 6.0.6 on 2026-06-07 01:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('disponivel', models.BooleanField(default=True)),
                ('autores', models.ManyToManyField(related_name='Livros', to='myapp.autor')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Livros', to='myapp.categoria')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Livro', to='myapp.editora')),
            ],
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edicao', models.PositiveIntegerField()),
                ('data_lancamento', models.DateField()),
                ('paginas', models.PositiveIntegerField()),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edition', to='myapp.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_membro', models.CharField(choices=[('ALUNO', 'Aluno'), ('FUNCIONÁRIO', 'Funcionário')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateField()),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EMITIDO', 'Emitido'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado'), ('REJEITADO', 'Rejeitado')], default='EMITIDO', max_length=20)),
                ('edicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros_emprestados', to='myapp.edicao')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_emprestados', to='myapp.livro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_emprestados', to='myapp.membro')),
            ],
        ),
    ]
