# Generated by Django 6.0.6 on 2026-06-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='ra',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='siape',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('EMITIDO', 'Emitido'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='EMITIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='membro',
            name='tipo_membro',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('ADMIN', 'Administrador')], max_length=20),
        ),
    ]
