# Generated by Django 6.0.6 on 2026-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_membro_ra_membro_siape_alter_emprestimo_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='edicao',
            options={'verbose_name': 'Edição', 'verbose_name_plural': 'Edições'},
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao_real',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
