# Generated by Django 6.0.6 on 2026-06-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_autor_options_alter_edicao_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_devolucao',
            new_name='data_devolucao_real',
        ),
    ]
