# Generated by Django 6.0.6 on 2026-06-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_data_devolucao_emprestimo_data_devolucao_real'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_devolucao_real',
            new_name='data_devolucao',
        ),
    ]
