# Generated by Django 6.0.6 on 2026-06-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_emprestimo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
