# Generated by Django 6.0.6 on 2026-06-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_membro_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
