# Generated by Django 6.0.6 on 2026-06-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_membro_email_membro_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='usuario',
        ),
    ]
