# Generated by Django 6.0.6 on 2026-06-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_membro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='edicao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='descricao',
        ),
        migrations.AddField(
            model_name='livro',
            name='qtd_disponivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='livro',
            name='qtd_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], default='EMPRESTADO', max_length=20),
        ),
        migrations.DeleteModel(
            name='Edicao',
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
    ]
