# Generated by Django 6.0.6 on 2026-06-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_emprestimo_edicao_remove_livro_editora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='qtd_total',
            field=models.PositiveIntegerField(db_column='quantidade_total', default=1),
        ),
    ]
