# Generated by Django 6.0.6 on 2026-06-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_livro_qtd_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='qtd_total',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade_total'),
        ),
    ]
