# Generated by Django 6.0.6 on 2026-06-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_livro_qtd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='qtd_disponivel',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade disponível'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='qtd_total',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade total'),
        ),
    ]
