# Generated by Django 6.0.6 on 2026-06-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_livro_capa_alter_livro_qtd_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
